apiVersion: v1
kind: Service
metadata:
  name: {{ include "cowboys.fullname" . }}
  labels:
    {{- include "cowboys.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "cowboys.selectorLabels" . | nindent 4 }}
