// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCowboy(ctx context.Context, arg CreateCowboyParams) (uuid.UUID, error)
	CreateGame(ctx context.Context, mode string) (uuid.UUID, error)
	CreateGameLog(ctx context.Context, arg CreateGameLogParams) (uuid.UUID, error)
	CreateManyCowboys(ctx context.Context, arg []CreateManyCowboysParams) *CreateManyCowboysBatchResults
	DeleteAllCowboys(ctx context.Context) (*Cowboy, error)
	GetGameById(ctx context.Context, id uuid.UUID) (*Game, error)
	GetRandomCowboy(ctx context.Context, id uuid.UUID) (*Cowboy, error)
	GetSingleAliveCowboyAndCount(ctx context.Context, id uuid.UUID) (*GetSingleAliveCowboyAndCountRow, error)
	GetSingleAliveCowboyById(ctx context.Context, id uuid.UUID) (*Cowboy, error)
	GetSingleCowboyByName(ctx context.Context, name string) (*Cowboy, error)
	GetSingleCowboyHealth(ctx context.Context, id uuid.UUID) (int32, error)
	ListAliveCowboys(ctx context.Context, arg ListAliveCowboysParams) ([]*Cowboy, error)
	ListGameLogsByGameId(ctx context.Context, arg ListGameLogsByGameIdParams) ([]*GameLog, error)
	ReduceCowboyHealth(ctx context.Context, arg ReduceCowboyHealthParams) error
	UpdateCowboyHealth(ctx context.Context, arg UpdateCowboyHealthParams) (*Cowboy, error)
	UpdateGameWinner(ctx context.Context, arg UpdateGameWinnerParams) error
}

var _ Querier = (*Queries)(nil)
