// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: github.com/sumlookup/cowboys/pb/cowboys.proto

package cowboys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{2}
}

type DamageExchange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From      string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To        string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value     int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *DamageExchange) Reset() {
	*x = DamageExchange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DamageExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageExchange) ProtoMessage() {}

func (x *DamageExchange) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageExchange.ProtoReflect.Descriptor instead.
func (*DamageExchange) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{3}
}

func (x *DamageExchange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DamageExchange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DamageExchange) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DamageExchange) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Cowboy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Health int32  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Damage int32  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *Cowboy) Reset() {
	*x = Cowboy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cowboy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cowboy) ProtoMessage() {}

func (x *Cowboy) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cowboy.ProtoReflect.Descriptor instead.
func (*Cowboy) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{4}
}

func (x *Cowboy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cowboy) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Cowboy) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DamageLog []*DamageExchange `protobuf:"bytes,1,rep,name=damage_log,json=damageLog,proto3" json:"damage_log,omitempty"`
	Winner    string            `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{5}
}

func (x *RunResponse) GetDamageLog() []*DamageExchange {
	if x != nil {
		return x.DamageLog
	}
	return nil
}

func (x *RunResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type ReloadDefaultCowboysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadDefaultCowboysRequest) Reset() {
	*x = ReloadDefaultCowboysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadDefaultCowboysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDefaultCowboysRequest) ProtoMessage() {}

func (x *ReloadDefaultCowboysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDefaultCowboysRequest.ProtoReflect.Descriptor instead.
func (*ReloadDefaultCowboysRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{6}
}

type ReloadDefaultCowboysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cowboys []*Cowboy `protobuf:"bytes,1,rep,name=cowboys,proto3" json:"cowboys,omitempty"`
}

func (x *ReloadDefaultCowboysResponse) Reset() {
	*x = ReloadDefaultCowboysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadDefaultCowboysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDefaultCowboysResponse) ProtoMessage() {}

func (x *ReloadDefaultCowboysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDefaultCowboysResponse.ProtoReflect.Descriptor instead.
func (*ReloadDefaultCowboysResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{7}
}

func (x *ReloadDefaultCowboysResponse) GetCowboys() []*Cowboy {
	if x != nil {
		return x.Cowboys
	}
	return nil
}

type GetCowboyByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCowboyByNameRequest) Reset() {
	*x = GetCowboyByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCowboyByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCowboyByNameRequest) ProtoMessage() {}

func (x *GetCowboyByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCowboyByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCowboyByNameRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{8}
}

func (x *GetCowboyByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCowboyByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cowboy *Cowboy `protobuf:"bytes,1,opt,name=cowboy,proto3" json:"cowboy,omitempty"`
}

func (x *GetCowboyByNameResponse) Reset() {
	*x = GetCowboyByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCowboyByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCowboyByNameResponse) ProtoMessage() {}

func (x *GetCowboyByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCowboyByNameResponse.ProtoReflect.Descriptor instead.
func (*GetCowboyByNameResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{9}
}

func (x *GetCowboyByNameResponse) GetCowboy() *Cowboy {
	if x != nil {
		return x.Cowboy
	}
	return nil
}

type ShootAtRandomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShooterId     string `protobuf:"bytes,1,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	ShooterName   string `protobuf:"bytes,2,opt,name=shooter_name,json=shooterName,proto3" json:"shooter_name,omitempty"`
	ShooterDamage int32  `protobuf:"varint,3,opt,name=shooter_damage,json=shooterDamage,proto3" json:"shooter_damage,omitempty"`
}

func (x *ShootAtRandomRequest) Reset() {
	*x = ShootAtRandomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootAtRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAtRandomRequest) ProtoMessage() {}

func (x *ShootAtRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAtRandomRequest.ProtoReflect.Descriptor instead.
func (*ShootAtRandomRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{10}
}

func (x *ShootAtRandomRequest) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

func (x *ShootAtRandomRequest) GetShooterName() string {
	if x != nil {
		return x.ShooterName
	}
	return ""
}

func (x *ShootAtRandomRequest) GetShooterDamage() int32 {
	if x != nil {
		return x.ShooterDamage
	}
	return 0
}

type ShootAtRandomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverHealth int32 `protobuf:"varint,1,opt,name=receiver_health,json=receiverHealth,proto3" json:"receiver_health,omitempty"`
}

func (x *ShootAtRandomResponse) Reset() {
	*x = ShootAtRandomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootAtRandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAtRandomResponse) ProtoMessage() {}

func (x *ShootAtRandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAtRandomResponse.ProtoReflect.Descriptor instead.
func (*ShootAtRandomResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{11}
}

func (x *ShootAtRandomResponse) GetReceiverHealth() int32 {
	if x != nil {
		return x.ReceiverHealth
	}
	return 0
}

var File_github_com_sumlookup_cowboys_pb_cowboys_proto protoreflect.FileDescriptor

var file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6d,
	0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4c,
	0x0a, 0x06, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x5d, 0x0a, 0x0b,
	0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x4c, 0x6f, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x1b, 0x52,
	0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62,
	0x6f, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x1c, 0x52, 0x65,
	0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f,
	0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x52, 0x07, 0x63, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x77, 0x62,
	0x6f, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x06, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x52,
	0x06, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x22, 0x7f, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x6f, 0x74,
	0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x6f, 0x74,
	0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x15, 0x53, 0x68, 0x6f, 0x6f,
	0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x32, 0x8c, 0x03, 0x0a, 0x0e, 0x43,
	0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x03, 0x52, 0x75, 0x6e, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x77, 0x62,
	0x6f, 0x79, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x65, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x77, 0x62,
	0x6f, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x77, 0x62, 0x6f, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63,
	0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x50, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x6f,
	0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74,
	0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x77,
	0x62, 0x6f, 0x79, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6d, 0x6c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2f, 0x70, 0x62, 0x3b, 0x63, 0x6f, 0x77,
	0x62, 0x6f, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescOnce sync.Once
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData = file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc
)

func file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP() []byte {
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescOnce.Do(func() {
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData)
	})
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData
}

var file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes = []interface{}{
	(*TestRequest)(nil),                  // 0: cowboys.TestRequest
	(*TestResponse)(nil),                 // 1: cowboys.TestResponse
	(*RunRequest)(nil),                   // 2: cowboys.RunRequest
	(*DamageExchange)(nil),               // 3: cowboys.DamageExchange
	(*Cowboy)(nil),                       // 4: cowboys.Cowboy
	(*RunResponse)(nil),                  // 5: cowboys.RunResponse
	(*ReloadDefaultCowboysRequest)(nil),  // 6: cowboys.ReloadDefaultCowboysRequest
	(*ReloadDefaultCowboysResponse)(nil), // 7: cowboys.ReloadDefaultCowboysResponse
	(*GetCowboyByNameRequest)(nil),       // 8: cowboys.GetCowboyByNameRequest
	(*GetCowboyByNameResponse)(nil),      // 9: cowboys.GetCowboyByNameResponse
	(*ShootAtRandomRequest)(nil),         // 10: cowboys.ShootAtRandomRequest
	(*ShootAtRandomResponse)(nil),        // 11: cowboys.ShootAtRandomResponse
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs = []int32{
	12, // 0: cowboys.DamageExchange.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: cowboys.RunResponse.damage_log:type_name -> cowboys.DamageExchange
	4,  // 2: cowboys.ReloadDefaultCowboysResponse.cowboys:type_name -> cowboys.Cowboy
	4,  // 3: cowboys.GetCowboyByNameResponse.cowboy:type_name -> cowboys.Cowboy
	2,  // 4: cowboys.CowboysService.Run:input_type -> cowboys.RunRequest
	6,  // 5: cowboys.CowboysService.ReloadDefaultCowboys:input_type -> cowboys.ReloadDefaultCowboysRequest
	8,  // 6: cowboys.CowboysService.GetCowboyByName:input_type -> cowboys.GetCowboyByNameRequest
	10, // 7: cowboys.CowboysService.ShootAtRandom:input_type -> cowboys.ShootAtRandomRequest
	0,  // 8: cowboys.CowboysService.Test:input_type -> cowboys.TestRequest
	5,  // 9: cowboys.CowboysService.Run:output_type -> cowboys.RunResponse
	7,  // 10: cowboys.CowboysService.ReloadDefaultCowboys:output_type -> cowboys.ReloadDefaultCowboysResponse
	9,  // 11: cowboys.CowboysService.GetCowboyByName:output_type -> cowboys.GetCowboyByNameResponse
	11, // 12: cowboys.CowboysService.ShootAtRandom:output_type -> cowboys.ShootAtRandomResponse
	1,  // 13: cowboys.CowboysService.Test:output_type -> cowboys.TestResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_sumlookup_cowboys_pb_cowboys_proto_init() }
func file_github_com_sumlookup_cowboys_pb_cowboys_proto_init() {
	if File_github_com_sumlookup_cowboys_pb_cowboys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DamageExchange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cowboy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadDefaultCowboysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadDefaultCowboysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCowboyByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCowboyByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootAtRandomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootAtRandomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes,
		DependencyIndexes: file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs,
		MessageInfos:      file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes,
	}.Build()
	File_github_com_sumlookup_cowboys_pb_cowboys_proto = out.File
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc = nil
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes = nil
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs = nil
}
