// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: github.com/sumlookup/cowboys/pb/cowboys.proto

package cowboys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{0}
}

type RunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{1}
}

type Cowboy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Health int32  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Damage int32  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *Cowboy) Reset() {
	*x = Cowboy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cowboy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cowboy) ProtoMessage() {}

func (x *Cowboy) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cowboy.ProtoReflect.Descriptor instead.
func (*Cowboy) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{2}
}

func (x *Cowboy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cowboy) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Cowboy) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type ReloadDefaultCowboysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadDefaultCowboysRequest) Reset() {
	*x = ReloadDefaultCowboysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadDefaultCowboysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDefaultCowboysRequest) ProtoMessage() {}

func (x *ReloadDefaultCowboysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDefaultCowboysRequest.ProtoReflect.Descriptor instead.
func (*ReloadDefaultCowboysRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{3}
}

type ReloadDefaultCowboysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cowboys []*Cowboy `protobuf:"bytes,1,rep,name=cowboys,proto3" json:"cowboys,omitempty"`
}

func (x *ReloadDefaultCowboysResponse) Reset() {
	*x = ReloadDefaultCowboysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadDefaultCowboysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDefaultCowboysResponse) ProtoMessage() {}

func (x *ReloadDefaultCowboysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDefaultCowboysResponse.ProtoReflect.Descriptor instead.
func (*ReloadDefaultCowboysResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadDefaultCowboysResponse) GetCowboys() []*Cowboy {
	if x != nil {
		return x.Cowboys
	}
	return nil
}

type ShootAtRandomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShooterId     string `protobuf:"bytes,1,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	GameId        string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ShooterName   string `protobuf:"bytes,3,opt,name=shooter_name,json=shooterName,proto3" json:"shooter_name,omitempty"`
	ShooterDamage int32  `protobuf:"varint,4,opt,name=shooter_damage,json=shooterDamage,proto3" json:"shooter_damage,omitempty"`
}

func (x *ShootAtRandomRequest) Reset() {
	*x = ShootAtRandomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootAtRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAtRandomRequest) ProtoMessage() {}

func (x *ShootAtRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAtRandomRequest.ProtoReflect.Descriptor instead.
func (*ShootAtRandomRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{5}
}

func (x *ShootAtRandomRequest) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

func (x *ShootAtRandomRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ShootAtRandomRequest) GetShooterName() string {
	if x != nil {
		return x.ShooterName
	}
	return ""
}

func (x *ShootAtRandomRequest) GetShooterDamage() int32 {
	if x != nil {
		return x.ShooterDamage
	}
	return 0
}

type ShootAtRandomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverHealth int32 `protobuf:"varint,1,opt,name=receiver_health,json=receiverHealth,proto3" json:"receiver_health,omitempty"`
}

func (x *ShootAtRandomResponse) Reset() {
	*x = ShootAtRandomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootAtRandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAtRandomResponse) ProtoMessage() {}

func (x *ShootAtRandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAtRandomResponse.ProtoReflect.Descriptor instead.
func (*ShootAtRandomResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{6}
}

func (x *ShootAtRandomResponse) GetReceiverHealth() int32 {
	if x != nil {
		return x.ReceiverHealth
	}
	return 0
}

type GetGameLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Sort   string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"` // asc or desc -- by created_at
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetGameLogsRequest) Reset() {
	*x = GetGameLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameLogsRequest) ProtoMessage() {}

func (x *GetGameLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameLogsRequest.ProtoReflect.Descriptor instead.
func (*GetGameLogsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameLogsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameLogsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetGameLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGameLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GameLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ShooterId      string                 `protobuf:"bytes,3,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Damage         int32                  `protobuf:"varint,5,opt,name=damage,proto3" json:"damage,omitempty"`
	ShooterHealth  int32                  `protobuf:"varint,6,opt,name=shooter_health,json=shooterHealth,proto3" json:"shooter_health,omitempty"`
	ReceiverHealth int32                  `protobuf:"varint,7,opt,name=receiver_health,json=receiverHealth,proto3" json:"receiver_health,omitempty"`
}

func (x *GameLog) Reset() {
	*x = GameLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLog) ProtoMessage() {}

func (x *GameLog) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLog.ProtoReflect.Descriptor instead.
func (*GameLog) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{8}
}

func (x *GameLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameLog) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

func (x *GameLog) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *GameLog) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *GameLog) GetShooterHealth() int32 {
	if x != nil {
		return x.ShooterHealth
	}
	return 0
}

func (x *GameLog) GetReceiverHealth() int32 {
	if x != nil {
		return x.ReceiverHealth
	}
	return 0
}

type GetGameLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameLogs   []*GameLog `protobuf:"bytes,1,rep,name=game_logs,json=gameLogs,proto3" json:"game_logs,omitempty"`
	Page       int32      `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalCount int32      `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *GetGameLogsResponse) Reset() {
	*x = GetGameLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameLogsResponse) ProtoMessage() {}

func (x *GetGameLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameLogsResponse.ProtoReflect.Descriptor instead.
func (*GetGameLogsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameLogsResponse) GetGameLogs() []*GameLog {
	if x != nil {
		return x.GameLogs
	}
	return nil
}

func (x *GetGameLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_github_com_sumlookup_cowboys_pb_cowboys_proto protoreflect.FileDescriptor

var file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6d,
	0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x75, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x06, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x1c, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x43,
	0x6f, 0x77, 0x62, 0x6f, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x22, 0x98,
	0x01, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x6f, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f,
	0x6f, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x6f,
	0x74, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x15, 0x53, 0x68, 0x6f,
	0x6f, 0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x6f, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xfc, 0x01, 0x0a,
	0x07, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x79, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xc9, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x77, 0x62, 0x6f,
	0x79, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x03, 0x52, 0x75, 0x6e,
	0x12, 0x13, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e,
	0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a,
	0x14, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e,
	0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77,
	0x62, 0x6f, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6f,
	0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x43, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x41, 0x74, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e,
	0x53, 0x68, 0x6f, 0x6f, 0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x53,
	0x68, 0x6f, 0x6f, 0x74, 0x41, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x75, 0x6d, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2f, 0x63, 0x6f, 0x77, 0x62, 0x6f,
	0x79, 0x73, 0x2f, 0x70, 0x62, 0x3b, 0x63, 0x6f, 0x77, 0x62, 0x6f, 0x79, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescOnce sync.Once
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData = file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc
)

func file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescGZIP() []byte {
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescOnce.Do(func() {
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData)
	})
	return file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDescData
}

var file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes = []interface{}{
	(*RunRequest)(nil),                   // 0: cowboys.RunRequest
	(*RunResponse)(nil),                  // 1: cowboys.RunResponse
	(*Cowboy)(nil),                       // 2: cowboys.Cowboy
	(*ReloadDefaultCowboysRequest)(nil),  // 3: cowboys.ReloadDefaultCowboysRequest
	(*ReloadDefaultCowboysResponse)(nil), // 4: cowboys.ReloadDefaultCowboysResponse
	(*ShootAtRandomRequest)(nil),         // 5: cowboys.ShootAtRandomRequest
	(*ShootAtRandomResponse)(nil),        // 6: cowboys.ShootAtRandomResponse
	(*GetGameLogsRequest)(nil),           // 7: cowboys.GetGameLogsRequest
	(*GameLog)(nil),                      // 8: cowboys.GameLog
	(*GetGameLogsResponse)(nil),          // 9: cowboys.GetGameLogsResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs = []int32{
	2,  // 0: cowboys.ReloadDefaultCowboysResponse.cowboys:type_name -> cowboys.Cowboy
	10, // 1: cowboys.GameLog.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: cowboys.GetGameLogsResponse.game_logs:type_name -> cowboys.GameLog
	0,  // 3: cowboys.CowboysService.Run:input_type -> cowboys.RunRequest
	3,  // 4: cowboys.CowboysService.ReloadDefaultCowboys:input_type -> cowboys.ReloadDefaultCowboysRequest
	5,  // 5: cowboys.CowboysService.ShootAtRandom:input_type -> cowboys.ShootAtRandomRequest
	7,  // 6: cowboys.CowboysService.GetGameLogs:input_type -> cowboys.GetGameLogsRequest
	1,  // 7: cowboys.CowboysService.Run:output_type -> cowboys.RunResponse
	4,  // 8: cowboys.CowboysService.ReloadDefaultCowboys:output_type -> cowboys.ReloadDefaultCowboysResponse
	6,  // 9: cowboys.CowboysService.ShootAtRandom:output_type -> cowboys.ShootAtRandomResponse
	9,  // 10: cowboys.CowboysService.GetGameLogs:output_type -> cowboys.GetGameLogsResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_github_com_sumlookup_cowboys_pb_cowboys_proto_init() }
func file_github_com_sumlookup_cowboys_pb_cowboys_proto_init() {
	if File_github_com_sumlookup_cowboys_pb_cowboys_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cowboy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadDefaultCowboysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadDefaultCowboysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootAtRandomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootAtRandomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes,
		DependencyIndexes: file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs,
		MessageInfos:      file_github_com_sumlookup_cowboys_pb_cowboys_proto_msgTypes,
	}.Build()
	File_github_com_sumlookup_cowboys_pb_cowboys_proto = out.File
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_rawDesc = nil
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_goTypes = nil
	file_github_com_sumlookup_cowboys_pb_cowboys_proto_depIdxs = nil
}
